from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import PostViewSet, CommentViewSet, PostListCreateView, PostDetailView, CommentListCreateView, CommentDetailView, like_post, unlike_post, UserFeedView

# Initialize the router
router = DefaultRouter()

# Register the Post and Comment viewsets with the router
router.register(r'posts', PostViewSet)
router.register(r'comments', CommentViewSet)

# Define the additional routes for liking/unliking and user feed
urlpatterns = [
    # Custom routes for liking/unliking posts and user feed
    path('posts/<int:pk>/like/', like_post, name='like-post'),
    path('posts/<int:pk>/unlike/', unlike_post, name='unlike-post'),
    path('feed/', UserFeedView.as_view(), name='user-feed'),

    # Routes for post and comment creation/retrieval
    path('posts/', PostListCreateView.as_view(), name='post-list-create'),
    path('posts/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('posts/<int:post_id>/comments/', CommentListCreateView.as_view(), name='comment-list-create'),
    path('posts/<int:post_id>/comments/<int:pk>/', CommentDetailView.as_view(), name='comment-detail'),
] + router.urls  # This will add all the routes generated by the router
